/**
 * Actions types used by Redux
 *
 */

export const GET_MERCHANTS_LIST_SUCCESS = 'GET_MERCHANTS_LIST_SUCCESS';
export const GET_MERCHANTS_LIST_FAILURE = 'GET_MERCHANTS_LIST_FAILURE';

export const DELETE_MERCHANT_SUCCESS = 'DELETE_MERCHANT_SUCCESS';
export const DELETE_MERCHANT_FAILURE = 'DELETE_MERCHANT_FAILURE';

export const ADD_MERCHANT_SUCCESS = 'ADD_MERCHANT_SUCCESS';
export const ADD_MERCHANT_FAILURE = 'ADD_MERCHANT_FAILURE';

export const UPDATE_MERCHANT_SUCCESS = 'UPDATE_MERCHANT_SUCCESS';
export const UPDATE_MERCHANT_FAILURE = 'UPDATE_MERCHANT_FAILURE';

export const UPDATE_PAGINATION_STATE = 'UPDATE_PAGINATION_STATE';